version: '3'
services:
    web:
        image: nginx
        depends_on:
            - application
            - redis
        volumes:
        - ./nginx/test.template:/etc/nginx/conf.d/mysite.template
        ports:
        - "80:80"
        environment:
        - NGINX_HOST=foobar.com
        - NGINX_PORT=80
        command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
    application:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - ./app:/app
        command: "/usr/bin/supervisord"
